package cn.berberman.fp.util

internal object BindException : Exception()